### ISSUE TITLE
Add initial values to `OptimisationResult`

### ISSUE THREAD

**Issue by brosaplanella** [paramm-team/pybamm-param#10]
Add initial values of optimisation variable and cost function to `OptimisationResult`.

**Comment by muhammedsogut** [comment]
I can add this to the #21 but in which format we want to show initial guesses and bounds:

{"parameter name": (initial guess, (lower bound, upper bound))} or
{"parameter name": initial guess}?

**Comment by brosaplanella** [comment]
I think the latter would be better. We can also include the bounds as a separate dictionary with tuples for upper and lower bounds.
