### ISSUE TITLE
Plotting is not working with multiple optimised variables

### ISSUE THREAD

**Issue by muhammedsogut** [paramm-team/pybamm-param#13]
The optimiser is able to perform multiple variables (e.g Negative electrode reaction coefficient, Negative electrode diffusivity [m2.s-1]...) but it cannot plot the final shape compared with the old one. When one variable is optimised it's working.

**Comment by muhammedsogut** [comment]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [10], in <module>
----> 1 result.plot()

File ~\Desktop\pbparam_test\pbparam\optimisation_result.py:43, in OptimisationResult.plot(self, testing)
     38 """
     39 Plot the optimisation result.
     40 """
     41 import matplotlib.pyplot as plt
---> 43 plot = self.optimisation_problem._plot(self.x)
     45 if not testing:  # pragma: no cover
     46     plt.show()

File ~\Desktop\pbparam_test\pbparam\optimisation_problems\data_fit.py:181, in DataFit._plot(self, x_optimal)
    175 def _plot(self, x_optimal):
    176     """
    177     Plot the optimisation result. Should be accessed through the OptimisationResult
    178     plot method.
    179     """
--> 181     initial_solution = self.calculate_solution()
    182     optimal_solution = self.calculate_solution(x_optimal)
    184     plot = pybamm.QuickPlot(
    185         [initial_solution, optimal_solution],
    186         output_variables=self.variables_optimise,
    187         labels=["Initial values", "Optimal values"],
    188     )

File ~\Desktop\pbparam_test\pbparam\optimisation_problems\data_fit.py:171, in DataFit.calculate_solution(self, parameters)
    168 else:
    169     t_eval = [0, self.data["Time [s]"].iloc[-1]]
--> 171 solution = self.simulation.solve(t_eval=t_eval, inputs=inputs)
    173 return solution

File ~\.conda\envs\MNS\lib\site-packages\pybamm\simulation.py:902, in Simulation.solve(self, t_eval, solver, check_model, save_at_cycles, calc_esoh, starting_solution, initial_soc, **kwargs)
    900 # Make sure we take at least 2 timesteps
    901 npts = max(int(round(dt / exp_inputs["period"])) + 1, 2)
--> 902 step_solution = solver.step(
    903     current_solution,
    904     model,
    905     dt,
    906     npts=npts,
    907     save=False,
    908     **kwargs,
    909 )
    910 steps.append(step_solution)
    911 current_solution = step_solution

File ~\.conda\envs\MNS\lib\site-packages\pybamm\solvers\base_solver.py:1215, in BaseSolver.step(self, old_solution, model, dt, npts, external_variables, inputs, save)
   1209 if old_solution is None:
   1210     # Run set up on first step
   1211     pybamm.logger.verbose(
   1212         "Start stepping {} with {}".format(model.name, self.name)
   1213     )
-> 1215     self.set_up(model, ext_and_inputs)
   1216     self.models_set_up.update(
   1217         {model: {"initial conditions": model.concatenated_initial_conditions}}
   1218     )
   1219     t = 0.0

File ~\.conda\envs\MNS\lib\site-packages\pybamm\solvers\base_solver.py:230, in BaseSolver.set_up(self, model, inputs, t_eval, ics_only)
    228         p_casadi[name] = casadi.MX.sym(name)
    229     else:
--> 230         p_casadi[name] = casadi.MX.sym(name, value.shape[0])
    231 p_casadi_stacked = casadi.vertcat(*[p for p in p_casadi.values()])
    232 # sensitivity vectors

IndexError: tuple index out of range

**Comment by muhammedsogut** [comment]
I cannot send the notebook file here :(

**Comment by muhammedsogut** [comment]
You can find the notebook here:
https://github.com/paramm-team/pybamm-param/blob/adding-test-notebooks/examples/notebooks/test_datafit.ipynb

**Comment by brosaplanella** [comment]
It should work now, can you try on branch `issue-13-plotting-not-working`?

**Comment by muhammedsogut** [comment]
Good work.

**Comment by brosaplanella** [comment]
Normally we don't close issues directly, but they are closed automatically when the associated PR is merged (e.g. in this case #16). If you can review it, I will merge it later today.

**Comment by muhammedsogut** [comment]
Ah sorry. I will review it now.
