### ISSUE TITLE
Setup_cost_function for OCP balance does not work for cathode

### ISSUE THREAD

**Issue by muhammedsogut** [paramm-team/pybamm-param#14]
setup_cost_function() within pbparam.OCPBalance works for anode but there is an error for cathode. The test notebook is:

https://github.com/paramm-team/pybamm-param/blob/adding-test-notebooks/examples/notebooks/test_ocp.ipynb

**Comment by brosaplanella** [comment]
That is what we discussed in the meeting, right?

**Comment by muhammedsogut** [comment]
Yes, this isssue has been resolved now.
