### ISSUE TITLE
Development install of `pbparam`, formalising requirements, and changing testing to nox.

### ISSUE THREAD

**Issue by PipGrylls** [paramm-team/pybamm-param#48]
Following a debug of a problem there are some structural changes and decisions that need to be made.

The current documentation uses `pip` to install `pybamm-param` from github and leaves the rest of the requirements to the user to figure out. (virtualenv is used which is excellent)

However, for development and testing we really should load pbparam via `pip install -e pbparam`. 

However, however, there are other package managers we could be using. 

pip - installed with python, standard, bit dated, PyPi

poetry - much more modern, really nice docs (https://python-poetry.org/docs/dependency-specification/#path-dependencies), not as widely used.

conda - widely used, strong dependancy resolution, often painfully slow, bloated

My recommendation would be to use pip or poetry.

To close this issue:

- [ ] Choose package manager
- [ ] Update docs to reflect change and correctly install development versions
- [ ] Create requirements file (dev and deploy)
- [ ] Plan a release pathway using chosen package manager

**Comment by brosaplanella** [comment]
PyBaMM uses pip, so I would choose it too for pbparam.

**Comment by PipGrylls** [comment]
Updating the title to better reflect the scope of the issue. 

- [ ] Make a requirements file with specifications for development and deployment.
- [ ] Document how to install the package for development.
- [ ] Move from tox to nox.
- [ ] Document how to publish the package and create releases.

**Comment by PipGrylls** [comment]
Updating the title to better reflect the scope of the issue, updating issues

- [x]  Make a requirements file --with specifications for development and deployment.--
- [x]  Document how to install the package for development.
- [x]  Move from tox to nox.
- [ ]  Document how to publish the package and create releases.
- [ ] Automate the requirement file generation on push to create a log of dependancies.

I’m adding a few things here, and changing some things to make more sense.

**Comment by PipGrylls** [comment]
Updating issues:

- [x]  Make a requirements file --with specifications for development and deployment.--
- [x]  Document how to install the package for development.
- [x]  Move from tox to nox.
- [ ]  Document how to publish the package and create releases.
- [x]  Automate the requirement file generation on push to create a log of dependancies.
 

Tox is fully deprecated by nox here, the development install is in the docs and the workflow runs

https://github.com/paramm-team/pybamm-param/commit/8b250b9a40c6e1b115aef07fe2d1fa923f076dc4

**Comment by PipGrylls** [comment]
@brosaplanella Please take a look at the PR this is done
