### ISSUE TITLE
Clean up stale branches

### ISSUE THREAD

**Issue by PipGrylls** [paramm-team/pybamm-param#58]
I’m not binning things that are from before I joined so review whats yours and delete (or PR) where appropriate:

The following are merged and well behind develop should be a simple delete:
issue-3-setup-docs
setup-hatch
issue-13-plotting-not-working

These have two commits ahead but are do behind I would probably just delete them:
define-package
23-mle-for-ocp-balance

This is 18 ahead but also 368 behind so @muhammedsogut should review this to determine what of the 18 ahead (if any are still relevent):
adding-test-notebooks

Finally, this is behind and called old main so i assume just delete:
old-main

**Comment by brosaplanella** [comment]
I have deleted:
* issue-3-setup-docs
* setup-hatch
* issue-13-plotting-not-working
* 23-mle-for-ocp-balance

I think the other two can also be deleted, but I will let @muhammedsogut check if there is something that can be rescued

**Comment by muhammedsogut** [comment]
I am reviewing them and I will delete them once it's done.

**Comment by muhammedsogut** [comment]
I removed the rest of the mentioned branches. I think these can be deleted as well:

44-updates-to-testing
define-package.

**Comment by PipGrylls** [comment]
44 I made today so that can stay define package can go

**Comment by PipGrylls** [comment]
Okay that looks good it looks like gitt-model needs a pull from main to keep it current but the repo looks much cleaner now. I will close this issue thanks all.
