### ISSUE TITLE
Test multivariable DataFit

### ISSUE THREAD

**Issue by brosaplanella** [paramm-team/pybamm-param#6]
The functionality for multivariable DataFit (e.g. voltage and temperature) should work, but has not been thoroughly tested. It would be good to add tests and examples about it.

**Comment by muhammedsogut** [comment]
PR 'issue:7 implement data fit to multiple measured variables #18' covers this issue.

**Comment by muhammedsogut** [comment]
It is closed as it's been solved by merge #18. The example algorithm is multiple_variable_fit.py
