### ISSUE TITLE
Update Python Versions

### ISSUE THREAD

**Issue by PipGrylls** [paramm-team/pybamm-param#61]
In 12 months 3.8 reaches EOL, 3.12 is now stable in bugfix, we are waiting on pybamm to update their requirements before introducing it.

**Comment by PipGrylls** [comment]
https://github.com/paramm-team/pybamm-param/commit/9b33c998687db960eff9e388935925680d9e06fb


Expected failures on 3.12

**Comment by brosaplanella** [comment]
The next PyBaMM release (to happen in the next couple of weeks) will support 3.12 so we might reconsider this issue.

**Comment by PipGrylls** [comment]
Agreed, although do we know if the package preventing PyBaMM from updating has been updated?

**Comment by brosaplanella** [comment]
I am not sure as they had a pre-release supporting 3.12 but it has been yanked. I would say let's hold this for now.

**Comment by PipGrylls** [comment]
This is fixed with #87
