### ISSUE TITLE
Implement data fit to multiple measured variables

### ISSUE THREAD

**Issue by brosaplanella** [paramm-team/pybamm-param#7]
At the moment the code only supports fitting to a single measured variable (e.g. voltage). The code should be extended to account for multiple measured variables (e.g. voltage and temperature).

Might be good to wait until #4 is done.

**Comment by muhammedsogut** [comment]
I have just updated the data_fit and it's working now. The test notebook is here:

https://github.com/paramm-team/pybamm-param/blob/%237-implement-data-fit-to-multiple-measured-variables/examples/notebooks/test_datafit.ipynb

**Comment by brosaplanella** [comment]
Can you create a branch with the example and open a PR?

**Comment by muhammedsogut** [comment]
Do you want me to put degC to K conversion if degC is supplied or is this the user issue as PyBamm only accepts K?

**Comment by brosaplanella** [comment]
For now let's leave it as a user problem. In the future, we can make sure that when experimental data is processed, the temperature in K is calculated (or we could also add temperature in degC in PyBaMM).
