### ISSUE TITLE
Release v0.1

### ISSUE THREAD

**Issue by brosaplanella** [paramm-team/pybamm-param#70]
We are approaching the time to make the first release for pbparam. We just need to wait for #21 and #63 to be merged, hopefully later this week.

Just opening this issue to track any other things we need to set up for the release so we can do it as soon as possible after the issues have been resolved.

**Comment by brosaplanella** [comment]
Quick update: we had a chat yesterday and we agreed that the release could take place after we have merged #71 (issue #21), which will hopefully be later today.

We will deal with the PyMOO examples later on, and we can always make a second release once the project is over.

**Comment by muhammedsogut** [comment]
Just merged the PR and I think we are ready for the release.
